### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by superkraft-io** [cyclic-software/s3fs#13]
![image](https://user-images.githubusercontent.com/109452239/213726631-a00330eb-af9f-48d2-8467-8ea4226af934.png)

Getting following error. How do I fix?

**Comment by superkraft-io** [comment]
This is the solution: https://github.com/uber-web/math.gl/issues/185#issuecomment-1135556234

**Comment by seekayel** [comment]
Thanks for following up and posting a solution. Closing out 👍
